# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60c35285a9813a040fc7a407aa4319d77de3a499dd7282ead1b6bf0cf5600327dddc3a14f0b683228ac41a8c6c4e7c34813214679be058d409be518f0a79ab22

test:
  secret_key_base: 9f23e2d4b3eac8193cabde66e44007ef4cca2eb7957525c0f0db8107c37d38f39260999700eec3c55474b9a596a55f9634822c77ba17cffc1aca071d14850c4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
